// Generated by CoffeeScript 1.10.0
(function() {
  var R, add_doctype, append, apply, concat, curryN, flip, get_head, get_html_text, metah, package_json, pipe, prepend, prop, wrap_in_html;

  metah = require('metah');

  R = require('ramda');

  append = R.append, apply = R.apply, concat = R.concat, curryN = R.curryN, flip = R.flip, pipe = R.pipe, prepend = R.prepend, prop = R.prop;

  package_json = require('./package.json');

  get_head = function(h) {
    var meta;
    meta = metah(h);
    return h('head', [meta.charset(), meta.author(package_json.author), meta.description(package_json.description), meta.http_equiv(), meta.viewport()]);
  };

  add_doctype = concat('<!doctype html>');

  get_html_text = prop('outerHTML');

  wrap_in_html = flip(append)([
    'html', {
      lang: 'en'
    }
  ]);

  module.exports = curryN(2, function(h, content) {
    var add_head, make_page_html;
    add_head = prepend(get_head(h));
    make_page_html = pipe(R.of, add_head, wrap_in_html, apply(h));
    return pipe(make_page_html, get_html_text, add_doctype)(content);
  });

}).call(this);
