// Generated by CoffeeScript 1.10.0
(function() {
  var flip, get_url_from_request, pipe, prop, ref, url;

  url = require('url');

  ref = require('ramda'), flip = ref.flip, pipe = ref.pipe, prop = ref.prop;

  get_url_from_request = pipe(prop('url'), flip(url.parse)(true));

  module.exports.path = pipe(get_url_from_request, prop('pathname'));

  module.exports.query = pipe(get_url_from_request, prop('query'));

}).call(this);
