// Generated by CoffeeScript 1.10.0
(function() {
  var curry;

  curry = require('ramda').curry;

  module.exports.html = curry(function(response, content) {
    response.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return response.end(content);
  });

  module.exports.json = curry(function(response, content) {
    response.writeHead(200, {
      'Content-Type': 'application/json'
    });
    return response.end(JSON.stringify(content));
  });

}).call(this);
