// Generated by CoffeeScript 1.10.0
(function() {
  var curry;

  curry = require('ramda').curry;

  module.exports.text_404 = curry(function(request, response) {
    response.writeHead(404, {
      'Content-Type': 'text/plain'
    });
    return response.end('Invalid path requested.');
  });

  module.exports.html_500 = function(message, log, request, response) {
    return function(err) {
      log.error(message, {
        err: err
      });
      response.writeHead(500, {
        'Content-Type': 'text/plain'
      });
      return response.end(err);
    };
  };

  module.exports.json_500 = function(message, log, request, response) {
    return function(err) {
      log.error(message, {
        err: err
      });
      response.writeHead(500, {
        'Content-Type': 'application/json'
      });
      return response.end(JSON.stringify({
        error: true,
        message: message
      }));
    };
  };

}).call(this);
