// Generated by CoffeeScript 1.10.0
(function() {
  var bunyan, h, hostname, http, listener, log, port, redis, redis_client, request_handler_maker, server;

  http = require('http');

  bunyan = require('bunyan');

  h = require('hyperscript');

  redis = require('redis');

  request_handler_maker = require('./server');

  log = bunyan.createLogger({
    level: 'trace',
    name: 'start_server'
  });

  redis_client = redis.createClient();

  redis_client.on('error', function(err) {
    return log.error('Redis client threw an error.', {
      err: err
    });
  });

  listener = request_handler_maker(redis_client);

  server = http.createServer(listener);

  hostname = 'localhost';

  port = 1337;

  server.listen(port, hostname, function() {
    return log.info("Started server listening on " + hostname + ":" + port + ".");
  });

}).call(this);
